name: Build, deploy to DEV
on:
  push:
    tags:
      - "*"
  pull_request:
    types: [opened, reopened]
  push:
    branches: [master,develop]

env:
  IMAGE: ms.auth

jobs:
  lint:
    name: Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Verify
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint] # Only run this workflow when "lint" workflow succeeds
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run unit tests
        run: |
          echo "TESTE - ${{ env.VERSION_NAME }}"
          echo "${{needs.lint.steps}}"
          echo "${{needs.lint.steps.get_version.outputs.VERSION}}"
          echo "${{steps}}"
          echo "${{steps.get_version.outputs.VERSION}}"

  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint, test]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run unit tests
        run: echo "PIRULITO - ${VERSION_NAME}"

  package:
    name: Package (docker)
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::develop
      - name: Run unit tests
        run: echo "PIRULITO - ${VERSION_NAME}"

  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: [package]

    steps:
      - name: Deploy service
        run: |
          echo "TESTE - ${VERSION_NAME}"
          echo "${{needs.package.steps}}"
          echo "${{needs.package.steps.get_version.outputs.VERSION}}"

